# check zookeeper status
# docker run --net=host --rm confluentinc/cp-zookeeper:5.3.1 bash -c "echo stat | nc localhost 2181 | grep Mode"
# docker run --net=host --rm confluentinc/cp-zookeeper:5.3.1 bash -c "echo stat | nc localhost 22181 | grep Mode"
# Mode: leader
# Mode: follower
#
# check kafka status
# docker logs kafka1 | grep started
# [2019-11-12 04:13:23,876] INFO [Kafka Server 1], started (kafka.server.KafkaServer)
#
# kafkacat -b localhost:9092 -L
# Metadata for all topics (from broker -1: localhost:9092/bootstrap):
# 3 brokers:
#  broker 2 at 127.0.0.1:9092
#  broker 3 at 127.0.0.1:9093
#  broker 1 at 127.0.0.1:9091
version: '3'
services:
  zk1:
    image: confluentinc/cp-zookeeper:5.3.1
    container_name: zk1
    hostname: zk1
    restart: unless-stopped
    ports:
      - 2181:2181
    environment:
      - ZOOKEEPER_SERVER_ID=1
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
      - ZOOKEEPER_INIT_LIMIT=5
      - ZOOKEEPER_SYNC_LIMIT=2
      - ZOOKEEPER_SERVERS=zk1:2888:3888;zk2:2888:3888
  zk2:
    image: confluentinc/cp-zookeeper:5.3.1
    container_name: zk2
    hostname: zk2
    restart: unless-stopped
    ports:
      - 2182:2182
    environment:
      - ZOOKEEPER_SERVER_ID=2
      - ZOOKEEPER_CLIENT_PORT=2182
      - ZOOKEEPER_TICK_TIME=2000
      - ZOOKEEPER_INIT_LIMIT=5
      - ZOOKEEPER_SYNC_LIMIT=2
      - ZOOKEEPER_SERVERS=zk1:2888:3888;zk2:2888:3888
  kafka1:
    image: confluentinc/cp-kafka:5.3.1
    container_name: kafka1
    hostname: kafka1
    ports:
      - 9091:9091
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ADVERTISED_LISTENERS=LISTENER_DOCKER_INTERNAL://kafka1:19091,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9091
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=LISTENER_DOCKER_INTERNAL
      - KAFKA_ZOOKEEPER_CONNECT=zk1:2181,zk2:2182
      - KAFKA_NUM_PARTITIONS=3
      - KAFKA_DEFAULT_REPLICATION_FACTOR=2
      - KAFKA_LOG4J_LOGGERS=kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO
    volumes:
      - ./kafka1/data:/var/lib/kafka/data
    depends_on:
      - zk1
      - zk2
  kafka2:
    image: confluentinc/cp-kafka:5.3.1
    container_name: kafka2
    hostname: kafka2
    ports:
      - 9092:9092
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_ADVERTISED_LISTENERS=LISTENER_DOCKER_INTERNAL://kafka2:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=LISTENER_DOCKER_INTERNAL
      - KAFKA_ZOOKEEPER_CONNECT=zk1:2181,zk2:2182
      - KAFKA_NUM_PARTITIONS=3
      - KAFKA_DEFAULT_REPLICATION_FACTOR=2
      - KAFKA_LOG4J_LOGGERS=kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO
    volumes:
      - ./kafka2/data:/var/lib/kafka/data
    depends_on:
      - zk1
      - zk2
  kafka3:
    image: confluentinc/cp-kafka:5.3.1
    container_name: kafka3
    hostname: kafka3
    ports:
      - 9093:9093
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_ADVERTISED_LISTENERS=LISTENER_DOCKER_INTERNAL://kafka3:19093,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=LISTENER_DOCKER_INTERNAL
      - KAFKA_ZOOKEEPER_CONNECT=zk1:2181,zk2:2182
      - KAFKA_NUM_PARTITIONS=3
      - KAFKA_DEFAULT_REPLICATION_FACTOR=2
      - KAFKA_LOG4J_LOGGERS=kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO
    volumes:
      - ./kafka3/data:/var/lib/kafka/data
    depends_on:
      - zk1
      - zk2
